version: '3.1'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: artify_db
    expose:
      - 5432

  web:
    container_name: image-repository
    build: .
    working_dir: /code/api
    environment:
      - FLASK_APP=./
      - FLASK_ENV=development
    ports:
      - 5000:5000
    volumes:
      - ./:/code
    depends_on:
      - postgres

#  elasticsearch:
#   image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
#   container_name: elasticsearch
#   environment:
#     - discovery.type=single-node
#   ports:
#     - 9200:9200
#   volumes:
#     - elasticsearch-data:/usr/share/elasticsearch/data
#
#volumes:
#  elasticsearch-data:
#    driver: local