version: '3.1'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: artify_db
    ports:
      - 5432:5432

  web:
    container_name: image-repository
    build: .
    working_dir: /code/api
    environment:
      - FLASK_APP=./
      - FLASK_ENV=development
    ports:
      - 5000:5000
    volumes:
      - ./:/code
    depends_on:
      - postgres
