services:
  # web:
  #   container_name: image-repository
  #   build: .
  #   environment:
  #     - FLASK_APP=app
  #     - FLASK_ENV=development
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - .:/code

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  
  frontend:
    container_name: frontend-nginx 
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./client:/www/data
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
      - API_PORT=5000
      - API_HOST=http://localhost

volumes:
  elasticsearch-data:
    driver: local